// playground/client/src/components/Embed/BEmbed.vue
<template>
  <component :is="tag" :class="wrapperClass">
    <component :is="type" v-bind="$attrs" :class="embedClasses">
      <slot v-if="type !== 'iframe'"></slot>
    </component>
  </component>
</template>

<script setup lang="ts">
import { defineComponent, h } from 'vue'
import "embed.scss"


// --- Constants ---
const TYPES = ['iframe', 'embed', 'video', 'object', 'img', 'b-img' 'b-img-lazy'] as const

const ASPECTS = ['21by9', '16by9', '4by3', '1by1'] as const

type EmbedType = typeof TYPES[number]
type AspectRatio = typeof ASPECTS[number]




export default defineComponent({
  name: 'BEmbed',
  props: {
    aspect: {
      type: String as () => AspectRatio,
      default: '16by9',
      validator: (value: string) => ASPECTS.includes(value as AspectRatio)
    },
    tag: {
      type: String,
      defualt: 'div'
    },
    type: {
      type: String as () => EmbedType,
      default: 'iframe',
      validator: (value: string) => TYPES.includes(value as AspectRatio)
    }
  },
  setup(props. { slots, attrs }){
  const resolvedType = computed(() => {
    props.type.startsWith('b') ?
      resolveBComponent(props.type) : props.type
  })

  const wrapperClasses = computed(() => [
    'embed-responsive',
    `embed-responsive-${aspect}`
  ])


  const embedClasses = computed(() => [
    'embed-responsive-item',
  ])

  return () =>
    h(
      props.tag,
      { class: wrapperClasses },
      h(props.type, { class: embedClasses, ...attrs }, slots.default?.())
    )

},

})


</script>

<style lang="postcss">
@import './embed.css'
</style>

// playground/client/src/components/Embed/BEmbed.tsx
import React,{ createElement, type FC } from 'react';
import { ASPECTS, TYPES, type EmbedType, type AspectRatio } from './types';
import "./embed.css"


interface BEmbedProps {
  aspect?: AspectRatio;
  tag?: keyof React.JSX.IntrinsicElements;// React.ElementType
  type?: EmbedType;
  src?: string;
  title?: string;
  children?: React.ReactNode;
  className?: string;
  [key: string]: any;
}

export const BEmbed: FC<BEmbedProps> = ({
  aspect = '16by9',
  tag = 'div',
  type = 'iframe',
  children,
  className = '',
  ...props
}) => {
  const wrapperClasses = [
    'embed-responsive',
    `embed-responsive-${aspect.replace('/', 'by')}`,
    className
  ].filter(Boolean).join(' ');

  const embedClasses = [
   'embed-responsive-item'
  ].join(' ');

  const resolvedType = type.startsWith('b-') ? 'img' : type;

  return createElement(
    tag, 
    { className: wrapperClasses },
    createElement(
      resolvedType,
      {
        className: embedClasses,
        ...props
      },
      type !== 'iframe' ? children : undefined
    )
  );
};
